server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestionBancariaSena
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true